namespace AngularApp1.Server.Models.DTO
{
    public class NewOrderDetailDTO
    {
        // Note: We don't need to add NewOrderDetailId as it's autogenerated in database
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int Price { get; set; }
    }
}
